version: "3.9"

services:
  notebook:
    build: .
    container_name: notebook
    ports:
      - 8888:8888
      - 4040:4040
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"
    volumes:
      - ./MAI5001:/home/jovyan/work

networks:
  default:
    name: mecai-network